name: Actualizar Historicos y Datos de Futbol

on:
  schedule:
    # Se ejecuta automáticamente todos los martes y viernes a las 4:00 AM UTC
    - cron: '0 4 * * 2,5'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña "Actions" en GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cop repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Ejecutar script de generacion de historicos
      env:
        API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
      run: |
        python generar_historicos.py

    - name: Configurar credenciales de Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Guardar y subir cambios al repositorio
      run: |
        git status
        git add data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualización automática de datos históricos (GitHub Actions)" && git push)
